### ISSUE TITLE
Embedded VS code fails with s3 as a stoage

### ISSUE THREAD

**Issue by romangoldberg** [kestra-io/storage-s3#33]
### Expected Behavior

Embedded VS code should properly work with S3 as a storage

### Actual Behaviour

Embedded VS code fails on {“message”:“Internal server error: Unable to execute HTTP request: Timeout waiting for connection from pool”,“_links”:{“self”:{“href”:“/api/v1/namespaces/merklecdp.identity/files?path=/README.md”}}} after some time of usage.

### Environment Information

- Kestra Version: 0.13
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): Kubernetes
- Java Version (If not docker):

**Comment by romangoldberg** [comment]
[kestra-webserver.log](https://github.com/kestra-io/storage-s3/files/13399857/kestra-webserver.log)

adding webserver log

**Comment by brian-mulier-p** [comment]
How often is the bug happening ? 
Do you manage to get the bug on your own or are you multiple people accessing namespace files at once to get it ? 
For it to work back again do you restart the instance or does it work again after a bit ?
How much files do you have on the concerned namespace ? Is it scoped to a particular namespace or it can happen on every ?
If it's scoped to a namespace, please provide a zipfile with content (or mocked content) of S3 storage under the "/merklecdp/identity/files" path ?

**Comment by romangoldberg** [comment]
Q: How often is the bug happening ?
A: It happened to me twice in 30 minutes
Q: Do you manage to get the bug on your own or are you multiple people accessing namespace files at once to get it ?
A: On my own
Q: For it to work back again do you restart the instance or does it work again after a bit ?
A: complete cleaning of indexeddb and browser data fixed the problem
Q:How much files do you have on the concerned namespace ? Is it scoped to a particular namespace or it can happen on every ?
A: normally we have like 3-4 flows
 Q: If it's scoped to a namespace, please provide a zipfile with content (or mocked content) of S3 storage under the "/merklecdp/identity/files" path ?
A: Its empty
